#!/usr/bin/env python3
# Extract the user's hand-drawn road strokes (PLAN_flyover_split_implementation.PNG)
# as POLYGONS in model meters -> ROOT/guide_roads.py (baked into the standalone).
# BLUE/RED = top-floor roads (z~48); PURPLE = ramp floor3->ground (z24->0).
import os, sys, io
import numpy as np, cv2
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IMG = os.path.join(ROOT, "renders", "PLAN_flyover_split_implementation.PNG")
OUT = os.path.join(ROOT, "guide_roads.py")
bgr = cv2.imread(IMG); H, W = bgr.shape[:2]
hsv = cv2.cvtColor(bgr, cv2.COLOR_BGR2HSV)

# calibrate px -> m via central oculus dots
white = cv2.inRange(hsv, (0, 0, 225), (180, 40, 255))
n, lab, st, _ = cv2.connectedComponentsWithStats(white)
dots = [(st[i,0]+st[i,2]/2, st[i,1]+st[i,3]/2) for i in range(1, n)
        if 40 < st[i,4] < 600 and 0.30*W < st[i,0]+st[i,2]/2 < 0.62*W]
dots.sort(key=lambda d: d[1])
aq, ula = dots[0], dots[-1]; x0 = np.mean([d[0] for d in dots])
s = (192.0 - (-191.0)) / (ula[1] - aq[1])
def to_m(pts):
    pts = pts.reshape(-1, 2).astype(float)
    return np.column_stack([(pts[:,0]-x0)*s, 192.0 - (pts[:,1]-aq[1])*s])
print(f"[ROADS] calib x0={x0:.0f} s={s:.3f}")

def seg(hlo, hhi, slo, vlo, vhi=255):
    return cv2.inRange(hsv, (hlo, slo, vlo), (hhi, 255, vhi))
COLORS = {
    "BLUE":   seg(100, 119, 90, 90),
    "RED":    cv2.bitwise_or(seg(0, 8, 110, 90), seg(160, 179, 110, 90)),
    "PURPLE": seg(120, 152, 55, 60),
}

def resample(poly, n):
    p = np.vstack([poly, poly[:1]])
    seg = np.hypot(np.diff(p[:, 0]), np.diff(p[:, 1]))
    cum = np.concatenate([[0], np.cumsum(seg)])
    s = np.linspace(0, cum[-1], n, endpoint=False)
    return np.column_stack([np.interp(s, cum, p[:, 0]), np.interp(s, cum, p[:, 1])])


def smooth(poly, it=3):
    out = poly.astype(float)
    for _ in range(it):
        out = (np.roll(out, 1, 0) + 2 * out + np.roll(out, -1, 0)) / 4.0
    return out


def polys_of(mask, amin_px=900):
    # close + smooth the blobby hand strokes -> neat road outlines
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, np.ones((13, 13), np.uint8))
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, np.ones((7, 7), np.uint8))
    mask = cv2.GaussianBlur(mask, (9, 9), 0)
    mask = (mask > 110).astype(np.uint8) * 255
    cn, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    out = []
    for c in cn:
        if cv2.contourArea(c) < amin_px:
            continue
        pm = to_m(c)                                   # all contour points -> meters
        per = np.hypot(*(pm - np.roll(pm, 1, 0)).T).sum()
        nseg = int(np.clip(per / 8.0, 24, 90))         # ~8 m vertex spacing
        out.append(smooth(resample(pm, nseg)).round(1))
    return out

ROADS = {k: polys_of(v) for k, v in COLORS.items()}
for k, ps in ROADS.items():
    print(f"[ROADS] {k}: {len(ps)} polys, verts={[len(p) for p in ps]}")

def fmt(poly):
    return "[" + ",".join(f"({x:.1f},{y:.1f})" for x, y in poly) + "]"
with open(OUT, "w", encoding="utf-8") as f:
    f.write("# AUTO-GENERATED by scripts/make_guide_roads.py — user's hand-drawn road guide.\n")
    f.write("# BLUE/RED = top-floor roads (z~48); PURPLE = ramp floor3->ground (z24->0).\n")
    f.write("# Polygons in model meters (origin=center, +Y=length).\n\n")
    for k in ("BLUE", "RED", "PURPLE"):
        f.write(f"{k}_POLYS = [\n")
        for p in ROADS[k]:
            f.write("  " + fmt(p) + ",\n")
        f.write("]\n\n")
print(f"[ROADS] wrote {OUT}")
